Repository legesher/legesher-docs, pull requests merged in 2019-11, with the labels that each got.

#69 docs: Rectified Typos and Improved Text
  guide/legesher/community-guide.md
  guide/legesher/idea-breakdown.md
  guide/legesher/roadmap.md
  guide/legesher/the-reason-why.md
Labels: 📖 Opportunity: Documentation

#71 Create .unibeautifyrc.json
  .unibeautifyrc.json
Labels: 💻 Opportunity: Code

#72 Update github configuration and update all-contributors
  .all-contributorsrc
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/ADD_DIALECT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/REVIEW_DIALECT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .unibeautifyrc.json
  LICENSE.md
  README.md
  guide/contributor/coding-style.md
  guide/contributor/contributor-toolbox.md
  guide/contributor/glossary.md
  guide/contributor/keyword-table.md
  guide/contributor/language-guide.md
  guide/contributor/style-guide.md
  guide/contributor/tree-sitter.md
  guide/legesher/community-guide.md
  guide/legesher/idea-breakdown.md
  guide/legesher/roadmap.md
  guide/legesher/the-reason-why.md
  package-lock.json
  package.json
Labels: 📆 Opportunity: Project Management

#76 Update config.yml
  .github/config.yml
Labels: 🖋 Opportunity: Content
