Repository legesher/legesher-docs, pull requests merged in 2019-10, with the labels that each got.

#23 feat: adding "Language: Ruby" to label gemfile
  guide/legesher/labels/rename-labels.rb
Labels: Good First Issue, Hacktoberfest, Language: Ruby, Opportunity: Great First Issue, Opportunity: Technical Beginner, Priority: Low, Status: On Hold, Type: Maintenance

#29 :memo: add translation guide
  guide/contributor/translation-guide.md
Labels: Hacktoberfest

#48 docs: Added full list of dialects from legesher-issue-labels.rb
  guide/legesher/labels/legesher-issue-labels.rb
  guide/legesher/roadmap.md
Labels: 📖 Opportunity: Documentation

#46 docs: :memo: Keyword table lang script + updated table
  guide/contributor/keyword-table.md
  lib/util/keywordTableLanguageScript.py
Labels: Hacktoberfest, Status: Completed, 💻 Opportunity: Code

#50 Update color for programming languages
  guide/legesher/roadmap.md
Labels: 📖 Opportunity: Documentation

#60 docs: improve documentation by fixing typos and mistakes
  guide/contributor/contributor-toolbox.md
  guide/contributor/language-guide.md
  guide/contributor/tree-sitter.md
Labels: 📖 Opportunity: Documentation

#62 Updated keyword-table.md
  guide/contributor/keyword-table.md
Labels: 💻 Opportunity: Code

#63 Minor Fix: :laptop: not rendered correctly
  README.md
Labels: Hacktoberfest, 🐛 Opportunity: Bug

#64 Update keyword-table.md
  guide/contributor/keyword-table.md
Labels: 💻 Opportunity: Code

#68 docs: add entries for more python keywords
  guide/contributor/keyword-table.md
Labels: Language: Python, 💻 Opportunity: Code
